# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/simon/Desktop/Homework4

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/simon/Desktop/Homework4

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/simon/Desktop/Homework4/CMakeFiles /home/simon/Desktop/Homework4//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/simon/Desktop/Homework4/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named my_project

# Build rule for target.
my_project: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 my_project
.PHONY : my_project

# fast build rule for target.
my_project/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_project.dir/build.make CMakeFiles/my_project.dir/build
.PHONY : my_project/fast

Device.o: Device.cpp.o
.PHONY : Device.o

# target to build an object file
Device.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_project.dir/build.make CMakeFiles/my_project.dir/Device.cpp.o
.PHONY : Device.cpp.o

Device.i: Device.cpp.i
.PHONY : Device.i

# target to preprocess a source file
Device.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_project.dir/build.make CMakeFiles/my_project.dir/Device.cpp.i
.PHONY : Device.cpp.i

Device.s: Device.cpp.s
.PHONY : Device.s

# target to generate assembly for a file
Device.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_project.dir/build.make CMakeFiles/my_project.dir/Device.cpp.s
.PHONY : Device.cpp.s

FileRepo.o: FileRepo.cpp.o
.PHONY : FileRepo.o

# target to build an object file
FileRepo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_project.dir/build.make CMakeFiles/my_project.dir/FileRepo.cpp.o
.PHONY : FileRepo.cpp.o

FileRepo.i: FileRepo.cpp.i
.PHONY : FileRepo.i

# target to preprocess a source file
FileRepo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_project.dir/build.make CMakeFiles/my_project.dir/FileRepo.cpp.i
.PHONY : FileRepo.cpp.i

FileRepo.s: FileRepo.cpp.s
.PHONY : FileRepo.s

# target to generate assembly for a file
FileRepo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_project.dir/build.make CMakeFiles/my_project.dir/FileRepo.cpp.s
.PHONY : FileRepo.cpp.s

Room.o: Room.cpp.o
.PHONY : Room.o

# target to build an object file
Room.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_project.dir/build.make CMakeFiles/my_project.dir/Room.cpp.o
.PHONY : Room.cpp.o

Room.i: Room.cpp.i
.PHONY : Room.i

# target to preprocess a source file
Room.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_project.dir/build.make CMakeFiles/my_project.dir/Room.cpp.i
.PHONY : Room.cpp.i

Room.s: Room.cpp.s
.PHONY : Room.s

# target to generate assembly for a file
Room.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_project.dir/build.make CMakeFiles/my_project.dir/Room.cpp.s
.PHONY : Room.cpp.s

Sensor.o: Sensor.cpp.o
.PHONY : Sensor.o

# target to build an object file
Sensor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_project.dir/build.make CMakeFiles/my_project.dir/Sensor.cpp.o
.PHONY : Sensor.cpp.o

Sensor.i: Sensor.cpp.i
.PHONY : Sensor.i

# target to preprocess a source file
Sensor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_project.dir/build.make CMakeFiles/my_project.dir/Sensor.cpp.i
.PHONY : Sensor.cpp.i

Sensor.s: Sensor.cpp.s
.PHONY : Sensor.s

# target to generate assembly for a file
Sensor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_project.dir/build.make CMakeFiles/my_project.dir/Sensor.cpp.s
.PHONY : Sensor.cpp.s

SmartHomeManager.o: SmartHomeManager.cpp.o
.PHONY : SmartHomeManager.o

# target to build an object file
SmartHomeManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_project.dir/build.make CMakeFiles/my_project.dir/SmartHomeManager.cpp.o
.PHONY : SmartHomeManager.cpp.o

SmartHomeManager.i: SmartHomeManager.cpp.i
.PHONY : SmartHomeManager.i

# target to preprocess a source file
SmartHomeManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_project.dir/build.make CMakeFiles/my_project.dir/SmartHomeManager.cpp.i
.PHONY : SmartHomeManager.cpp.i

SmartHomeManager.s: SmartHomeManager.cpp.s
.PHONY : SmartHomeManager.s

# target to generate assembly for a file
SmartHomeManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_project.dir/build.make CMakeFiles/my_project.dir/SmartHomeManager.cpp.s
.PHONY : SmartHomeManager.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_project.dir/build.make CMakeFiles/my_project.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_project.dir/build.make CMakeFiles/my_project.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_project.dir/build.make CMakeFiles/my_project.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... my_project"
	@echo "... Device.o"
	@echo "... Device.i"
	@echo "... Device.s"
	@echo "... FileRepo.o"
	@echo "... FileRepo.i"
	@echo "... FileRepo.s"
	@echo "... Room.o"
	@echo "... Room.i"
	@echo "... Room.s"
	@echo "... Sensor.o"
	@echo "... Sensor.i"
	@echo "... Sensor.s"
	@echo "... SmartHomeManager.o"
	@echo "... SmartHomeManager.i"
	@echo "... SmartHomeManager.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

